fail_fast: false
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
       - id: trailing-whitespace
       - id: end-of-file-fixer
       - id: forbid-submodules # I hate submodules - Ian
       - id: mixed-line-ending
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
